# a basic function for echo
# build: docker build -t functions/echo .
# example: docker run functions/echo
# example: docker run functions/echo hello there
FROM alpine
ENTRYPOINT [ "/bin/echo" ]
CMD ["hello"]